#!/bin/bash

cd
rm -rf AUTORUN-CCMINER-JAK1.2
git clone https://github.com/pichetx/AUTORUN-CCMINER-JAKKARIN
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-JAKKARIN/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining
cd
cd ../bin
rm -rf add-ip edit-miner run-miner update down-grade
cd
cd AUTORUN-CCMINER-JAKKARIN
chmod +x setupdate.sh
sh setupdate.sh
